//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication9.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Designers
    {
        public Designers()
        {
            this.FashionShow = new HashSet<FashionShow>();
        }
    
        public int DesignerID { get; set; }
        public string DesignerName { get; set; }
        public string DesignerLastName { get; set; }
        public int DesignerPhone { get; set; }



        [DisplayName("Password :")]
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "This part is Required.")]
        public int DesignerPassword { get; set; }
        [Required(ErrorMessage ="This part is Required.")]
        [DisplayName("E-Mail :  ")]
        public string DesignerEmail { get; set; }
        public string LoginErrorMessage { get; set; }

        public virtual ICollection<FashionShow> FashionShow { get; set; }
    }
}
