//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication9.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FashionShow
    {
        public int FashionShowID { get; set; }
        public string FashionShowName { get; set; }
        public Nullable<System.DateTime> FashionShowDate { get; set; }
        public int ModelID { get; set; }
        public int DesignerID { get; set; }
    
        public virtual Designers Designers { get; set; }
        public virtual Models Models { get; set; }
    }
}
